#!/bin/bash

self_dir=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")

# directories with texmfcnf.lua, in order of priority:
# /etc/context/texmfcnf.lua
# ~/.config/context/texmfcnf.lua (or the XDG equivalent)
export TEXMFCNF TEXMFCACHE TEXMFDOTDIR TEXMF TEXMFCONTEXT OSFONTDIR
: "${TEXMFCNF:="${XDG_CONFIG_HOME:-$HOME/.config}/context;/etc/context"}"
: "${TEXMFCACHE:=${XDG_CACHE_HOME:-$HOME/.cache}}"
: "${TEXMFDOTDIR:="."}"
: "${TEXMF:="\$TEXMFCONTEXT"}"
: "${TEXMFCONTEXT:="selfautodir:share/context/texmf"}"
: "${OSFONTDIR:="/usr/share/fonts//;${XDG_DATA_HOME:-$HOME/.local/share}/fonts//"}"

# run with argv[0] = mtxrun, which makes luametatex run the mtxrun.lua file in its directory
exec -a "${BASH_SOURCE[0]}" "$self_dir/luametatex" "$@"
